name: omise_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  yaml: ^3.1.0
  path: ^1.8.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
