name: Dart CI

on: [push, pull_request]

jobs:
  build_dart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.0"

      - name: Install dependencies
        run: |
          dart pub get
          cd example/flutter_example
          flutter pub get

      - name: Analyze (Check if distributable for Dart)
        run: dart analyze

      - name: Run Tests
        run: dart test

      - name: Analyze (Check if distributable for Flutter)
        run: |
          cd example/flutter_example
          flutter analyze
