name: Dart CI

on: [push, pull_request]

jobs:
  build_dart:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.0"

      - name: Install dependencies
        run: |
          ls
          cd omise-dart
          dart pub get

      - name: Analyze (Check if distributable for Dart)
        run: |
          cd omise-dart
          dart analyze

      - name: Run Tests
        run: |
          cd omise-dart
          dart test

      - name: Analyze (Check if distributable for Flutter)
        run: |
          cd example/flutter_example
          flutter analyze
